# ExFat appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'
image: Visual Studio 2017

install:
  - git submodule update --init --recursive

before_build:
  nuget restore

notifications:
  provider: Slack
  auth_token:
      secure: tv8q1S0sKJGnirkiriCf+BEXA1+EyX7TOBtHyp/hBqqnkk97Eaf1BJRR7iQONe7nCKK10lHcBdmFA1UXD49CL1hXpCk1Rdto8mhH8eodczQ=
  channel: '#build'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release
platform: Any CPU

build:
  parallel: true
#  publish_nuget: true
#  publish_nuget_symbols: true
  verbosity: minimal
  project: ExFat.sln

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false
